name: paint_scanner
description: "Color image recognition."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  gal: ^2.2.3
  google_mobile_ads: ^4.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"  