name: paint_scanner
description: "Color image recognition."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_paypal: ^0.2.0
  gal: ^2.2.3
  google_mobile_ads: ^4.0.0
  http: ^0.13.6
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"  